files:
  - source: /web/locale/Hasadee Library.pot
    translation: /web/locale/%two_letters_code%/LC_MESSAGES/Hasadee Library.po
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
